/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { King } from "./King";
export type { KingVestingPool } from "./KingVestingPool";
export type { MintableERC20 } from "./MintableERC20";
